version: 0.2

phases:
  install:
    commands:
      - echo "Installing zip..."
      - apt-get update -y
      - apt-get install -y zip

  pre_build:
    commands:
      - echo "Creating zip archive..."
      - zip -r website.zip .

  build:
    commands:
      - echo "Encoding zip to Base64..."
      - ZIP_BASE64=$(base64 website.zip)

      - echo "Detecting EC2 instance with tag Name=MyServer..."
      - INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=MyServer" "Name=instance-state-name,Values=running" \
          --query "Reservations[0].Instances[0].InstanceId" \
          --output text)

      - echo "Deploying to instance: $INSTANCE_ID"

  post_build:
    commands:
      - echo "Sending deployment via SSM..."
      - aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Website" \
          --parameters '{"commands": [
              "echo '"$ZIP_BASE64"' | base64 -d > /tmp/website.zip",
              "sudo apt-get update -y",
              "sudo apt-get install unzip -y",
              "sudo rm -rf /var/www/html/*",
              "sudo unzip /tmp/website.zip -d /var/www/html/"
          ]}' \
          --region ap-south-1

artifacts:
  files:
    - website.zip
