version: 0.2

phases:
  install:
    commands:
      - echo "Installing zip package"
      - yum install -y zip

  build:
    commands:
      - echo "Zipping web folder"
      - ls -R
      - zip -r web.zip web/

artifacts:
  files:
    - web.zip
