version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - yum install -y unzip zip jq
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - echo "Running Terraform apply..."
      - cd Terraform
      - terraform init
      - terraform apply -auto-approve
      - INSTANCE_ID=$(terraform output -raw instance_id)
      - cd ..

  build:
    commands:
      - echo "Preparing HTML content..."
      - HTML_CONTENT=$(<web/index.html)

  post_build:
    commands:
      - echo "Deploying HTML to EC2 via SSM..."
      - |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy HTML" \
          --parameters 'commands=[
            "sudo yum install -y nginx",
            "sudo systemctl enable nginx",
            "sudo systemctl start nginx",
            "echo '"$HTML_CONTENT"' | sudo tee /usr/share/nginx/html/index.html"
          ]' \
          --region ap-south-1

artifacts:
  files:
    - '**/*'
