version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y unzip zip wget jq
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - cd Terraform
      - terraform init
      - terraform apply -auto-approve
      - INSTANCE_ID=$(terraform output -raw instance_id)
      - cd ..

  build:
    commands:
      - echo "Zipping website folder..."
      - zip -r website.zip web/*

  post_build:
    commands:
      - echo "Deploying website to EC2 via SSM..."
      - aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Website" \
          --parameters '{"commands": [
              "sudo yum install -y nginx",
              "sudo systemctl enable nginx",
              "sudo systemctl start nginx",
              "sudo rm -rf /usr/share/nginx/html/*",
              "sudo unzip /codebuild/output/src*/website.zip -d /usr/share/nginx/html/"
          ]}' \
          --region ap-south-1

artifacts:
  files:
    - '**/*'
